import time

def euler26():
    '''	
    A unit fraction contains 1 in the numerator. The decimal representation of the unit fractions with denominators 2 to 10 are given:

    1/2	= 	0.5
    1/3	= 	0.(3)
    1/4	= 	0.25
    1/5	= 	0.2
    1/6	= 	0.1(6)
    1/7	= 	0.(142857)
    1/8	= 	0.125
    1/9	= 	0.(1)
    1/10	= 	0.1
    Where 0.1(6) means 0.166666..., and has a 1-digit recurring cycle. It can be seen that 1/7 has a 6-digit recurring cycle.

    Find the value of d < 1000 for which 1/d contains the longest recurring cycle in its decimal fraction part.
    '''
    aradigim_deger = 0 
    aradigim_dongu_sayisi = 0
    for i in range(2, 1000):                                                                                                             
        kalanlar = []
        kalan = (10**len(str(i))) % i                  
        while kalan not in kalanlar:     
            kalanlar.append(kalan)                                           
            if kalan == 0:
                break
            while kalan < i:
                kalan *= 10                                                      
            kalan = kalan % i                                                                        
        while kalanlar[0] != kalan:
            kalanlar.remove(kalanlar[0]) 
        if len(kalanlar) > aradigim_dongu_sayisi:
            aradigim_dongu_sayisi = len(kalanlar)
            aradigim_deger = i
    print (aradigim_deger)
    print (aradigim_dongu_sayisi)
def euler27(): 
    '''
    Euler olağanüstü ikinci dereceden formülü keşfetti: n**2 + n + 41
    Formülün, 0≤n≤39 ardışık tamsayı değerleri için 40 asal üreteceği ortaya çıktı. 
    Bununla birlikte, n = 40, 40**2 + 40 + 41 = 40 (40 + 1) +41, 41 ile bölünebilir 
    ve kesinlikle n = 41, 41**2 + 41 + 41 açıkça 41 ile bölünebilir. 
    
    İnanılmaz formül n**2 − 79n + 1601 keşfedildi , 
    0≤n≤79 ardışık değerleri için 80 asal üretir. 

    Katsayıların çarpımı −79 ve 1601, −126479'dur. 
    Formun ikinci dereceden ele alındığında: n**2 + an + b, 
    burada | a | <1000 ve | b | ≤ 1000 
    burada | n | n'nin modül / mutlak değeridir, 
    ör. | 11 | = 11 ve | −4 | = 4 
    n = 0'dan başlayarak ardışık n değerleri için maksimum asal sayısını üreten ikinci dereceden ifade için a ve b katsayılarının çarpımını bulun.
    
    
    '''	
    def asal_mi(say):
        karekok = int(round(abs(say**0.5)))
        #print(type(karekok))
        for a in range(2,karekok+1):
            if say % a == 0:
                return False
            else:
                continue
        else:
            return True
    
    mx1 = (0,0,0)
    for a in range(-1000,1000):
        for b in range(-1000,1001):
            for n in range(81):
                frm = n**2 + a*n + b
                #print(type(frm))
                if asal_mi(frm):
                    continue
                else: 
                    deg = (a,b,n)
                    if mx1[2] < deg[2]:
                        mx1 = deg
                        print('yeni deger', deg)
                        break
                    else:
                        break
    print('son değer', mx1)
    print(mx1[0]*mx1[1])
def euler28():
    kosegen = 0
    x = 1
    kosegen += x
    for n in range(1,501):
        for i in range(4):
            x += 2*n 
            kosegen += x
    print(kosegen)
def euler29():
    '''
    Consider all integer combinations of a**b for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:

    2**2=4, 2**3=8, 2**4=16, 2**5=32
    3**2=9, 3**3=27, 3**4=81, 3**5=243
    4**2=16, 4**3=64, 4**4=256, 4**5=1024
    5**2=25, 5**3=125, 5**4=625, 5**5=3125
    If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:

    4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125

    How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

    '''
    distinctterms = set()
    for a in range (2,101):
        for b in range(2,101):
            distinctterms.add(a**b)
    print(len(distinctterms))
def euler30():
    a = 0
    for i in range(2,10_000_000):
    
        birler 		= i%10
        onlar 		= (i//10)%10
        yuzler 		= (i//100)%10
        binler 		= (i//1000)%10
        ybinler 	= (i//10000)%10
        milyonlar 	= (i//100000)%10
        if (birler**5+onlar**5+yuzler**5+binler**5+ybinler**5+milyonlar**5) == i:
            print(i)
            a = a+i
    print (a)


#euler26()
#euler27()
#euler28()
#euler29()
#euler30()
